services:
  mysql:
    container_name: mysql
    image: mysql
    #    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=mySQL@8080
      - MYSQL_USER=root
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql
    restart: unless-stopped
networks:
  mysql:
    driver: bridge

volumes:
  mysql: