eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka

spring:
  application:
    name: api-gateway
#defining routes of our services
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product #  (Load balanced URL for the "products" service)
          predicates:
            - Path=/api/v1/products # This predicate matches requests with the path /api/v1/products and routes them to the "products" service.
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/v1/order
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/api/v1/inventories
#re-routing the eureka server port to be accessible through the api gateway
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
#loading the static files(CSS) of the eureka server
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8443/realms/online-store-microservices-docker
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0


# increase the logging level -> to understand what is going on behind the sciences
#  RouteDefinitionLocator is responsible for handle the routes for a request
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: Info
    org.springframework.cloud.gateway: TRACE
