spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: mySQL@8080
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8010

#  CREATE USER 'test'@'172.17.0.1' IDENTIFIED BY 'YES';
#
#  GRANT ALL PRIVILEGES ON *.* TO 'test'@'172.17.0.1' WITH GRANT OPTION;
#
#  flush privileges;