eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka

spring:
  application:
    name: notification
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    integration:
      enable: true
    sampler:
      probability: 1.0

  #KAFKA Properties
  kafka:
    bootstrap-servers: localhost:29092
    template:
      default-topic: notificationTopic
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping:
                event: com/iyex/notification/event/OrderPlacedEvent
      group-id: notificationId


server:
  port: 0

