spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
    password: mySQL@8080
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: order
server:
  port: 8020

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
