spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: mySQL@8080
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: inventory

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka