spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: mySQL@8080
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: inventory

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8030
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
